services:
  - type: web
    name: shazam-bot
    env: python
    buildCommand: "pip install --upgrade pip && pip install --only-binary=:all: shazamio pyTelegramBotAPI flask"
    startCommand: "python main.py"

 
