services:
  - type: web
    name: shazam-bot
    env: python
    buildCommand: "apt-get update && apt-get install -y curl && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && export PATH='$HOME/.cargo/bin:$PATH' && pip install -r requirements.txt"
    startCommand: "python main.py"
